export default  {
    products:[{
        _id:'1',
        name:'Nike shirt',
        category: 'Shirt',
        image:'/images/d1.jpg',
        price:58.99,
        brand:'Nike',
        rating: 4.5,
        numReviews: 330,
        countInStock:6,
    },
    {
        _id:'2',
        name:'Adidas Shirt',
        category: 'Shirt',
        image:'/images/d1.jpg',
        price:59.9,
        brand:'Adidas',
        rating: 4.8,
        numReviews: 290,
        countInStock:6,
    },
    {
        _id:'3',
        name:'Sport Pants',
        category: 'Pant',
        image:'/images/d1.jpg',
        price:34.99,
        brand:'Puma',
        rating: 4.4,
        numReviews: 190,
        countInStock:6,
    },
    {
        _id:'4',
        name:'Best Pants',
        category: 'Pant',
        image:'/images/d1.jpg',
        price:43.99,
        brand:'Nike',
        rating: 4.9,
        numReviews: 490,
        countInStock:6,
    },
    {
        _id:'5',
        name:'Best Pants',
        category: 'Pant',
        image:'/images/d1.jpg',
        price:43.99,
        brand:'Nike',
        rating: 4.9,
        numReviews: 490,
        countInStock:6,
    },
    {
        _id:'6',
        name:'Best Pants',
        category: 'Pant',
        image:'/images/d1.jpg',
        price:43.99,
        brand:'Nike',
        rating: 4.9,
        numReviews: 490,
        countInStock:6,
    },
    {
        _id:'7',
        name:'Best Pants',
        category: 'Pant',
        image:'/images/d1.jpg',
        price:43.99,
        brand:'Nike',
        rating: 4.9,
        numReviews: 490,
        countInStock:6,
    },{
        _id:'8',
        name:'Best Pants',
        category: 'Pant',
        image:'/images/d1.jpg',
        price:43.99,
        brand:'Nike',
        rating: 4.9,
        numReviews: 490,
        countInStock:6,
    }]
}